### ISSUE TITLE
Dockerhub Image Plans

### ISSUE THREAD

**Issue by palladionIT** [ethanopp/fitly#11]
Hello,

Thanks for the great project! I was wondering if there are plans to push a finished image to docker hub to make running everything a lot easier?

**Comment by ethanopp** [comment]
Hey @palladionIT 

Just set one up here:
https://hub.docker.com/repository/docker/ethanopp/fitly

...will update readme instructions shortly

**Comment by palladionIT** [comment]
Okay great! Thank you very much!
