### ISSUE TITLE
Error pulling oura data: Unknown string format: 2019-01-07T03:

### ISSUE THREAD

**Issue by pierretamisier** [ethanopp/fitly#2]
First, great work on the project, it's really good and exactly the kind of thing I'm looking for!

I deployed fitly locally on ubuntu 18.04 using run-fitly-dev. After entering my Oura keys and athlete information I can pull the oura data for the dashboard but it keeps failing in ouraAPI.py in the function pull_activity_data(oura, days_back=7).

```
def pull_activity_data(oura, days_back=7):
...
        df_activity_summary['day_end_local'] = pd.to_datetime(df_activity_summary['day_end'].apply(lambda x: x[:-6]))
...
```

Everytime I attempt the refresh the data I receive the following error:

```
Error pulling oura data: Unknown string format: 2019-01-07T03:
```

I'll keep digging and revert back with my findings.

Also, I'm interested in knowing if anyone manages to use ptvsd for debugging and how. At the moment I'm using print() everywhere and it makes me sad to not use an actual debugger.

**Comment by ethanopp** [comment]
Hey Pierre thanks!

I had some lazily written code in there dealing with datetimes but just pushed a potential fix for this.

Pull the latest and do a 'Truncate All' in the settings page and let me know if you still get the error.

Also I use PyCharm for my development so have never used ptvsd

...sometimes print statements are way to go - I find myself often just looking at the logs in this project (which are just print statements to a file)

**Comment by pierretamisier** [comment]
Cheers. This [commit](https://github.com/ethanopp/fitly/commit/9f8794526658571948306864c3d7346207bf46cb) fixed the issue!
