### ISSUE TITLE
Odd PMC Scaling

### ISSUE THREAD

**Issue by kateweber-dg** [ethanopp/fitly#23]
Hello! I am having fun with this tool (and will bring a PR with some minor tweaks to the Withings API in the next little while) - but I'm getting a view of the PMC that is weirdly compressed relative to the view the demo screenshots show.  I've explored `performance.py` but haven't located the values that might be controlling this. Can you point me in the right direction?

![Screenshot at 2022-11-29 10-09-07](https://user-images.githubusercontent.com/104510852/204566553-b9a73e12-2e01-4012-89ae-11879c0b0695.png)

**Comment by ethanopp** [comment]
Glad you're enjoying it! I unfortunately have not had time to keep maintaining this for a while so there are definitely a handful of updates that need to be made... oura api has changed, withings api...etc.

The figure that gets created for the pmc chart can be found here: https://github.com/ethanopp/fitly/blob/41fca15e8b8f677868d3c13544a7aa2d2804a347/src/fitly/pages/performance.py#L2226
