### ISSUE TITLE
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite Date type only accepts Python date objects as input.

### ISSUE THREAD

**Issue by pierretamisier** [ethanopp/fitly#5]
Hello,

I think the commit [67bef5cbd62218a50a4bcb2e5af8c80b329deb3f](https://github.com/ethanopp/fitly/commit/67bef5cbd62218a50a4bcb2e5af8c80b329deb3f) breaks the build. When I deploy this version locally (run-fitly-dev) I cannot update the Birthday in settings anymore and get a callback error in the UI.

Steps to reproduce the issue:

```
(env) pierre@pierre-thinkpad:~/Workspace/fitly(master)$ rm config/fitness.db 
(env) pierre@pierre-thinkpad:~/Workspace/fitly(master)$ git checkout 67bef5cbd62218a50a4bcb2e5af8c80b329deb3f .
(env) pierre@pierre-thinkpad:~/Workspace/fitly(master)$ run-fitly-dev
```

I delete the db to make sure I'm using clean data, and that everything I'm as a first time user in the app works.

Go to settings and enter my birthday, click ok.
![image](https://user-images.githubusercontent.com/45526746/90051342-679b8900-dc8c-11ea-8bb6-76763b5f38f8.png)
![image](https://user-images.githubusercontent.com/45526746/90051393-7aae5900-dc8c-11ea-9bf9-6afb01d7c767.png)

I also can reproduce this issue by cloning the repo again from scratch and deploying the app.

**Comment by ethanopp** [comment]
Thanks @pierretamisier 

Should now be fixed in https://github.com/ethanopp/fitly/commit/0b0d98b9fba07c982b641d67116f0e9de4865721

**Comment by pierretamisier** [comment]
Indeed! Thanks
