### ISSUE TITLE
Strava activity stream has not attribute 'keys' - Cannot generate df_samples

### ISSUE THREAD

**Issue by pierretamisier** [ethanopp/fitly#8]
First thing - I'm trying to understand the strava data scraping while I'm having issues with the below code.
```
def build_df_samples(self):
        seconds = 1
        streams = get_strava_client().get_activity_streams(self.id, types=types)
        self.df_samples = pd.DataFrame(columns=types)
        # Write each row to a dataframe
        for item in types:
            if item in streams.keys():
                self.df_samples[item] = pd.Series(streams[item].data, index=None)
```
Which will return a "...has no attribute keys()" error when pulling strava data.
I can add a "if streams..." before the for loop as a workaround but then the df_sample is empty and the below line fails:
```
self.df_samples = self.df_samples.resample(str(seconds) + 'S').mean()
```
Throwing:
```Error pulling strava data: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Float64Index'```

I'll keep digging and will revert back with my findings. I haven't finished investigating but it seems to be happening on all activities.

Second thing - As a side note, I have old data only with time and nothing else. That might trigger a problem down the line. Example:
![image](https://user-images.githubusercontent.com/45526746/90081922-5d48b180-dcc3-11ea-818b-b820c78dd8f2.png)

**Comment by ethanopp** [comment]
Could you just try printing out the result of streams and make sure you're getting data back from the strava request?

All that code you pasted is doing is parsing through the json response and putting into a df per the 'types' specified at the top of the file:
```
types = ['time', 'latlng', 'distance', 'altitude', 'velocity_smooth', 'heartrate', 'cadence', 'watts', 'temp',
         'moving', 'grade_smooth']
```

**Comment by pierretamisier** [comment]
**Streams = None** for the sample workout I posted above in the screenshot.
I'm looking at a way to query all my strava workouts without any streams to check if I see any patterns. I wouldn't be surprised if my first few Garmin workouts from 2007 are rubbish :) Will let you know.

Curious to see how TrainingPeaks or GoldenCheetah handle those cases. I know TP accommodates massively for poor data recording and inaccuracies.

**Comment by ethanopp** [comment]
I believe I do (or did) have some code in here that accommodates for bad stream data... mainly for runs/rides outside where signal may have gotten lost, [interpolate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html) the gaps between the stream... but I have not done anything to handle workouts where there is no stream at all... if it is an issue just with old workouts, you can set the 'activities_after_date' for strava in the config.ini to a later date

**Comment by pierretamisier** [comment]
Agreed. I think it's fair as of now not to import activities without any streams. Looking at old data it seems to be happening on 100s of data files.

And to be honest I completely missed out on the API rate limit. I never hit until now it since I was trying to retrieve all my data from years back, which is impossible with 100 calls per 15min!

One of my goals is to analyze my PMC over the last few years of training and racing as I do in GoldenCheetah. But that's another story.

Thanks for your help on this issue!
